# Generated by Django 2.2.7 on 2020-01-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(default='No description yet.')),
                ('notification', models.TextField(default='No notification yet.')),
                ('reference', models.TextField(default='No reference yet.')),
                ('code', models.CharField(default='', max_length=8, unique=True)),
                ('user', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
