# Generated by Django 2.2.7 on 2020-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='No description yet.')),
                ('due_time', models.DateTimeField(auto_now=True)),
                ('release_time', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(upload_to='uploads/assignment/')),
                ('week_id', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(default='No description yet.')),
                ('files', models.FileField(upload_to='uploads/week/')),
                ('course_id', models.CharField(default='', max_length=8, unique=True)),
                ('status', models.BooleanField(default='False')),
                ('release_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='history_notification',
            field=models.TextField(default='No notification yet.'),
        ),
    ]
