# Generated by Django 3.0.1 on 2020-01-04 15:11

from django.db import migrations, models
import teachers.models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20200102_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week',
            name='files',
            field=models.FileField(upload_to=teachers.models.upload_to),
        ),
    ]
