# Generated by Django 3.0.1 on 2020-01-05 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_assignment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='teachers.Course'),
        ),
    ]
