# Generated by Django 2.2.7 on 2020-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_reg',
            name='student_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
