# Generated by Django 2.2.7 on 2020-01-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('files', models.FileField(upload_to='uploads/assignment/')),
                ('annotation', models.TextField()),
                ('comment', models.TextField()),
                ('feedback', models.TextField()),
                ('score', models.CharField(max_length=10)),
                ('status', models.BooleanField(default='False')),
                ('assignment_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.BooleanField(default='False'),
        ),
    ]
